- name: Ensure root user .bashrc exists
  file:
    path: /root/.bashrc 
    state: touch

- name: Customise bash prompt for root user
  lineinfile:
    dest: /root/.bashrc 
    line: "{{ ps1 }}"
    owner: root
