- name: Create the user account
  user:
    name: ops
    shell: /bin/bash
    groups: wheel

- name: Add authorized ssh key
  authorized_key:
    user: ops
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    exclusive: yes

- name: Enable sudo for the ops group 
  copy:
    content: "%ops ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/ops
    mode: 600
