- name: Provisioning script for vfx studio soe 
  hosts: all
  roles:
    - role: bash 
      when: ansible_virtualization_type == "docker"
    - role: jumpcloud-agent
      when: ansible_virtualization_type != "docker"
    - role: ops-user 
      when: ansible_virtualization_type != "docker"
